### ISSUE TITLE
Add this project to `awesome promise`.

### ISSUE THREAD

**Issue by magicdawn** [William17/taxi#1]
https://github.com/wbinnssmith/awesome-promises#strict-implementations

写的很好, 建议加入到 Awesome Promises.

**Comment by magicdawn** [comment]
在 [CNode](https://cnodejs.org/topic/5603cb8a152fdd025f0f5014) 上看的中文注释版...
才发现源码是E文版...

**Comment by William17** [comment]
hi，谢谢，谢谢建议
已经加入到官方的实现列表 [implementations page.](https://promisesaplus.com/implementations)

CNode 那里我的确是用中文注释编辑过，因为CNode里有些兄弟英文暂时还很不好呢，哈哈
